#!/bin/bash
if [[ $1 < $2 ]]
then
	echo "$1"
elif [[ $1 > $2 ]]
then
	echo "$2"
elif [[ $1 = $2 ]]
then
	echo "An error occured" >&2 
elif [[ $# != 2 ]]
then
        echo "An error occured" >&2
else
	echo "An error occured" >&2
fi
